# -*- coding: utf-8 -*-
"""demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1S3LCTZ2AE8oTthE_uVbOQMlT4N0Vx_
"""

# infer.py
import torch
import timm
import sys
from PIL import Image
from torchvision import transforms

MODEL_PATH = "models/vit_after.pt"
CLASS_NAMES = open("datasets/classname.txt").read().splitlines()
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

image_path = sys.argv[1]

model = timm.create_model(
    "vit_tiny_patch16_224",
    pretrained=False,
    num_classes=len(CLASS_NAMES)
)
model.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
model.to(DEVICE).eval()

tf = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485,0.456,0.406],[0.229,0.224,0.225])
])

img = Image.open(image_path).convert("RGB")
x = tf(img).unsqueeze(0).to(DEVICE)

with torch.no_grad():
    prob = torch.softmax(model(x), dim=1)
    top_p, top_i = torch.topk(prob, k=3)

print("\nTop-3 Predictions:")
for i in range(3):
    print(f"{i+1}. {CLASS_NAMES[top_i[0][i]]} — {top_p[0][i]:.4f}")